server:
  port: 8400
spring:
  application:
    name: notification-service
  kafka:
    bootstrap:
      servers: https://localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/notifications
    username: zeyad
    password: password
  jpa:
    database: POSTGRESQL
    show-sql : true
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/EGX-AI
  mail:
    host: smtp.gmail.com
    port: 578
    username: zeyad10101@gmail.com
    password: ibdq ddvq xnss pggn
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    url: jdbc:postgresql://localhost:5432/notifications
    user: zeyad
    password: password
    sql-migration-prefix: V
    repeatable-sql-migration-prefix: R
    sql-migration-separator: __
    sql-migration-suffixes: .sql
eureka:
  client:
  serviceUrl:
    defaultZone: http://localhost:8761/eureka

